import type {Metadata} from "next";

import "../globals.css";
import {ModeToggle} from "../components/navbar/theme";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

export default function SignInLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="relative">
      <div className="flex items-center justify-end py-3 px-4 absolute top-2 right-2">
        <ModeToggle />
      </div>
      <div className="w-10/12 sm:w-8/12 mx-auto flex flex-col h-screen justify-center">{children}</div>
    </section>
  );
}
