import type {Metadata} from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

export default function SignInLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      {" "}
      <div className="w-8/12 mx-auto my-14">{children}</div>
    </section>
  );
}
