import React from "react";
import Sidebar from "../components/sidebar/Sidebar";
import {Metadata} from "next";
import {ScrollArea} from "@/components/ui/scroll-area";
import {getAllCategory} from "../actions/category";
import {getUserFromToken} from "../actions/cookie";
export const metadata: Metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategory();
  const user = await getUserFromToken();
  return (
    <section className="flex w-full items-center pt-4 px-4">
      <Sidebar categories={categories?.data} user={user} />
      <div className="w-9/12 pl-6 col-span-10">
        <ScrollArea className="h-[calc(100vh-20px)]">{children}</ScrollArea>
      </div>
    </section>
  );
}
