import React from "react";
import Sidebar from "../components/Sidebar";
import {Metadata} from "next";
import {ScrollArea} from "@/components/ui/scroll-area";
export const metadata: Metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="grid grid-cols-12 pt-4 px-4">
      <div className=" col-span-2">
        <Sidebar />
      </div>
      <div className="col-span-10 pl-6">
        <ScrollArea className="h-[calc(100vh-20px)]">{children}</ScrollArea>
      </div>
    </section>
  );
}
