import React from "react";
import Sidebar from "../components/sidebar/Sidebar";
import {Metadata} from "next";
import {ScrollArea} from "@/components/ui/scroll-area";
import {getAllCategory} from "../actions/category";
import {getUserFromToken} from "../actions/cookie";
import {ModeToggle} from "../components/navbar/theme";
import MobileNav from "../components/navbar/MobileNav";
export const metadata: Metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategory();
  const user = await getUserFromToken();
  return (
    <section className="flex w-full items-center pt-4 ">
      <Sidebar categories={categories?.data} user={user} />
      <div className="w-11/12 md:w-9/12 col-span-12 md:col-span-10 mx-auto">
        <ScrollArea className="h-[calc(100vh-20px)]">
          <div className="flex items-center justify-between md:justify-end">
            <MobileNav />
            <ModeToggle />
          </div>
          {children}
        </ScrollArea>
      </div>
    </section>
  );
}
